// framework/src/components/ContextMenu.vue
<!--
  - Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
  -->

<script setup lang="ts">
import { useContextMenu } from '@/hooks/useContextMenu';
import { ref } from 'vue';
import { t } from '@/i18n';

interface MenuItem {
    label: string;
    key: string;
    action?: (...args: any[]) => void;
}
defineProps<{ menuItems: MenuItem[] }>();
const emit = defineEmits(['select']);

const containerRef = ref<HTMLElement>();
const { x, y, visible, setVisible } = useContextMenu(containerRef.value, '.can-right-click');

function clickMenuItem(item: MenuItem): void {
    setVisible(false);
    emit('select', item);
    if (item?.action && typeof item.action === 'function') {
        item.action();
    }
}
</script>

<template>
    <div class="container" ref="containerRef">
        <slot></slot>
        <Teleport to="body">
            <div class="context-menu" v-if="visible" :style="{ left: `${x}px`, top: `${y}px` }">
                <div class="context-menu-item" v-for="item in menuItems" :key="item.label" @mousedown.stop @click="clickMenuItem(item)">
                    {{ t(item.label) }}
                </div>
            </div>
        </Teleport>
    </div>
</template>

<style scoped>
.context-menu {
    z-index: 99999;
    position: fixed;
    min-width: 150px;
    padding: 4px 0;
    overflow: hidden;
    font-size: 12px;
    color: var(--mi-text-color-primary);
    border-radius: var(--mi-border-radius-base);
    background-color: var(--menu-bg-color);
    box-shadow: var(--mi-box-shadow);
    transition: all 0.1s ease;
}

.context-menu-item {
    padding: 8px 12px;
    user-select: none;
}

.context-menu-item:hover {
    background-color: var(--mi-color-primary);
    color: #ffffff;
}
</style>

// modules/leaks/src/components/ContextMenu.tsx
/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 */
import React, { useRef, useEffect } from 'react';
import styled from '@emotion/styled';
import { Session } from '../entity/session';
import { runInAction } from 'mobx';
import { observer } from 'mobx-react';

interface Position {
    x: number;
    y: number;
};

export interface MenuItemModel {
    label: React.ReactNode;
    key: string;
    action: () => void;
    visible?: boolean;
    disabled?: boolean;
}

const MenuItem = styled.div`
    padding: 4px 16px;
    color: ${(props): string => props.theme.textColorPrimary};

    &:not(.disabled):hover{
      background: ${(props): string => props.theme.primaryColorHover};
      color: #ffffff;
    }
    &.disabled{
        color: ${(props): string => props.theme.textColorDisabled};
    }
`;

function closeMenu(session: Session): void {
    runInAction(() => {
        session.contextMenu.visible = false;
    });
}

// 调整菜单位置：不要超出窗口
function adjustMenuPosition({ session, menu, xPos, yPos }: {
    session: Session;
    menu: HTMLDivElement;
    xPos: Position['x'];
    yPos: Position['y'];
}): void {
    const winWidth = document.documentElement.clientWidth || document.body.clientWidth;
    const winHeight = document.documentElement.clientHeight || document.body.clientHeight;
    let x = xPos;
    let y = yPos;
    if (x + menu.offsetWidth >= winWidth) {
        x -= menu.offsetWidth;
    }
    if (y + menu.offsetHeight > winHeight) {
        y -= menu.offsetHeight;
    }
    runInAction(() => {
        session.contextMenu.xPos = x;
        session.contextMenu.yPos = y;
    });
    menu.focus();
};

const MenuContainer = styled.div`
    padding: 3px 0;
    min-width: 100px;
    border-radius: ${(props): string => props.theme.borderRadiusBase};
    background-color:  ${(props): string => props.theme.contextMenuBgColor};
    position: fixed;
    z-index: 99999;
    box-shadow: ${(props): string => props.theme.boxShadowLight};
    user-select: none;
`;
interface IProps {
    session: Session;
    menuItems: MenuItemModel[];
}
const Menu = ({ session, menuItems }: IProps): JSX.Element => {
    const menuRef = useRef<HTMLDivElement>(null);
    const { contextMenu } = session;
    const handleMouseDown = (e: MouseEvent): void => {
        if ((e.target as HTMLElement)?.parentNode !== menuRef.current) {
            closeMenu(session);
        }
    };

    const handleCloseMenu = (): void => {
        closeMenu(session);
    };

    useEffect(() => {
        window.addEventListener('mousedown', handleMouseDown);
        window.addEventListener('wheel', handleCloseMenu);

        return () => {
            window.removeEventListener('mousedown', handleMouseDown);
            window.removeEventListener('wheel', handleCloseMenu);
        };
    });
    useEffect(() => {
        const menu = menuRef.current;
        if (contextMenu.visible && menu !== null) {
            adjustMenuPosition({ session, menu, xPos: contextMenu.xPos, yPos: contextMenu.yPos });
        }
    }, [contextMenu.visible, contextMenu.xPos, contextMenu.yPos]);
    return (
        contextMenu.visible && menuItems.length > 0
            ? <MenuContainer ref={menuRef} style={{ left: `${contextMenu.xPos}px`, top: `${contextMenu.yPos}px` }} tabIndex={-1} onBlur={(): void => { closeMenu(session); }} >
                {menuItems.map((item: MenuItemModel): JSX.Element => (
                    <MenuItem className={`menu-item ${item.disabled ? 'disabled' : ''}`} key={item.key}
                        onClick={(): void => {
                            if (item.disabled) {
                                return;
                            }
                            item.action();
                            closeMenu(session);
                        }}>
                        {item.label}
                    </MenuItem>))}
            </MenuContainer>
            : <></>
    );
};

export const ContextMenu = observer(Menu);
